global:
  resolve_timeout: 5m
  smtp_from: 787129204@qq.com
  smtp_smarthost: smtp.qq.com:587
  smtp_auth_username: 787129204@qq.com
  smtp_auth_password: xwnsbsvkzbftbbbh
route:
  receiver: web.hook
  routes:
  - receiver: sh000001_<_5_increase
    group_by:
    - strategy_id
    match:
      strategy_id: sh000001_<_5_increase
    group_interval: 5m
    repeat_interval: 1s
  - receiver: alertmanagerrule-sample
    group_by:
    - strategy_id
    match:
      strategy_id: alertmanagerrule-sample
    group_interval: 5m
    repeat_interval: 1d
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    url: http://127.0.0.1:5001/
- name: sh000001_<_5_increase
  email_configs:
  - send_resolved: false
    to: 915917782@qq.com
- name: alertmanagerrule-sample
  email_configs:
  - send_resolved: false
    to: 915917782@qq.com
    headers:
      Subject: '{{ template "email.custom.subject" . }}'
    html: '{{ template "email.custom.html" . }}'
  webhook_configs:
  - send_resolved: false
    url: ""
templates: []
